# EVN

In [3]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [4]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10     #5x4 행렬 (-0.9 ~ 1)
hidden

array([[-0.8, -0.8,  0.6,  0.1],
       [ 0.6, -0.6, -0.9,  0.5],
       [-0.4, -0.7,  0.3,  0.8],
       [ 0.5,  0.2,  0.5, -0.6],
       [-0.7,  0.1,  0.4,  0.7]])

## element wise sum

In [5]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

(array([[ 0.9, -0.5,  0.4, -0.9],
        [-0.2, -0.2, -0.5,  0.4],
        [-0.3, -0.8, -0.2,  0.9],
        [-0.2, -0.5, -0.6,  0.8],
        [ 0.4,  0.9,  0.3,  0.4]]),
 array([[ 0.1, -1.3,  1. , -0.8],
        [ 0.4, -0.8, -1.4,  0.9],
        [-0.7, -1.5,  0.1,  1.7],
        [ 0.3, -0.3, -0.1,  0.2],
        [-0.3,  1. ,  0.7,  1.1]]))

In [6]:
arg = np.random.randint(-9, 10, (1, 4)) / 10    #1x4행렬이지만 2 3 4 5 행을 1행과 같은 수로 채워서 계산
arg, hidden + arg

(array([[-0.7, -0.9, -0.3,  0.5]]),
 array([[-1.5, -1.7,  0.3,  0.6],
        [-0.1, -1.5, -1.2,  1. ],
        [-1.1, -1.6,  0. ,  1.3],
        [-0.2, -0.7,  0.2, -0.1],
        [-1.4, -0.8,  0.1,  1.2]]))

In [7]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

(array([[-0.8],
        [-0.7],
        [-0.2],
        [ 0. ],
        [-0.9]]),
 array([[-1.6, -1.6, -0.2, -0.7],
        [-0.1, -1.3, -1.6, -0.2],
        [-0.6, -0.9,  0.1,  0.6],
        [ 0.5,  0.2,  0.5, -0.6],
        [-1.6, -0.8, -0.5, -0.2]]))

In [8]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

(array([[-0.2]]),
 array([[-1. , -1. ,  0.4, -0.1],
        [ 0.4, -0.8, -1.1,  0.3],
        [-0.6, -0.9,  0.1,  0.6],
        [ 0.3,  0. ,  0.3, -0.8],
        [-0.9, -0.1,  0.2,  0.5]]))

In [9]:
hidden + 1

array([[0.2, 0.2, 1.6, 1.1],
       [1.6, 0.4, 0.1, 1.5],
       [0.6, 0.3, 1.3, 1.8],
       [1.5, 1.2, 1.5, 0.4],
       [0.3, 1.1, 1.4, 1.7]])

In [10]:
1 + hidden

array([[0.2, 0.2, 1.6, 1.1],
       [1.6, 0.4, 0.1, 1.5],
       [0.6, 0.3, 1.3, 1.8],
       [1.5, 1.2, 1.5, 0.4],
       [0.3, 1.1, 1.4, 1.7]])

## element wise multiplication

In [11]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

(array([[-0.7, -0.2, -0.9,  0.1],
        [-0.6,  0.6,  0.9, -0.2],
        [ 0.1, -0.8, -0.2,  0. ],
        [ 0.9,  0.1,  0.8,  0.9],
        [ 0.4, -0.4,  0.6,  0.4]]),
 array([[ 0.56,  0.16, -0.54,  0.01],
        [-0.36, -0.36, -0.81, -0.1 ],
        [-0.04,  0.56, -0.06,  0.  ],
        [ 0.45,  0.02,  0.4 , -0.54],
        [-0.28, -0.04,  0.24,  0.28]]))

In [12]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

(array([[ 0.9,  0.9,  0.4, -0.2]]),
 array([[-0.72, -0.72,  0.24, -0.02],
        [ 0.54, -0.54, -0.36, -0.1 ],
        [-0.36, -0.63,  0.12, -0.16],
        [ 0.45,  0.18,  0.2 ,  0.12],
        [-0.63,  0.09,  0.16, -0.14]]))

In [13]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

(array([[ 0.3],
        [ 0.4],
        [ 0.2],
        [-0.6],
        [-0.4]]),
 array([[-0.24, -0.24,  0.18,  0.03],
        [ 0.24, -0.24, -0.36,  0.2 ],
        [-0.08, -0.14,  0.06,  0.16],
        [-0.3 , -0.12, -0.3 ,  0.36],
        [ 0.28, -0.04, -0.16, -0.28]]))

In [14]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

(array([[-0.3]]),
 array([[ 0.24,  0.24, -0.18, -0.03],
        [-0.18,  0.18,  0.27, -0.15],
        [ 0.12,  0.21, -0.09, -0.24],
        [-0.15, -0.06, -0.15,  0.18],
        [ 0.21, -0.03, -0.12, -0.21]]))

In [15]:
hidden * 2

array([[-1.6, -1.6,  1.2,  0.2],
       [ 1.2, -1.2, -1.8,  1. ],
       [-0.8, -1.4,  0.6,  1.6],
       [ 1. ,  0.4,  1. , -1.2],
       [-1.4,  0.2,  0.8,  1.4]])

In [16]:
2 * hidden

array([[-1.6, -1.6,  1.2,  0.2],
       [ 1.2, -1.2, -1.8,  1. ],
       [-0.8, -1.4,  0.6,  1.6],
       [ 1. ,  0.4,  1. , -1.2],
       [-1.4,  0.2,  0.8,  1.4]])

## matrix multiplication

In [17]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[ 0.8,  0.2, -0.5, -0.2,  0.4],
        [-0.4,  0.9,  0.1, -0.3,  0.1],
        [ 0.5,  0.1,  0. , -0.7,  0.3],
        [-0.2, -0.8,  0.5,  0.6,  0.8]]),
 array([[-0.04, -0.9 ,  0.37,  0.04, -0.14],
        [ 0.17, -0.91, -0.11,  0.99,  0.31],
        [-0.05, -1.32,  0.53,  0.56,  0.5 ],
        [ 0.69,  0.81, -0.53, -0.87, -0.11],
        [-0.54, -0.57,  0.71,  0.25,  0.41]]))

In [18]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[-0.04, -0.9 ,  0.37,  0.04, -0.14],
       [ 0.17, -0.91, -0.11,  0.99,  0.31],
       [-0.05, -1.32,  0.53,  0.56,  0.5 ],
       [ 0.69,  0.81, -0.53, -0.87, -0.11],
       [-0.54, -0.57,  0.71,  0.25,  0.41]])